### ISSUE TITLE
black texture

### ISSUE THREAD

**Issue by NekkonXD** [nillerusr/srceng-android#1]
On chapter 7 & 8 almost all textures are black.
On other chapter its not black.
There's a way to fix it by typing mat_hdr_level 1 on console (im using mat_hdr_level 2). But it makes the  game looks ugly. 
Is there a fix for this or its just my phone problem?

Here's  a pic:
![Screenshot_20200811-114459](https://user-images.githubusercontent.com/69495363/89855336-cc8dab00-dbc8-11ea-9099-983baefc801f.png)

![Screenshot_20200811-114736](https://user-images.githubusercontent.com/69495363/89855361-dfa07b00-dbc8-11ea-8412-1e9c47bd8729.png)

My device  is J2 Prime and i got 20-50 fps with max settings.

**Comment by nillerusr** [comment]
I know about that problem.

**Comment by nillerusr** [comment]
Original version for android has the same problem. Its works propertly on tegra and some other gpu's. In portal all textures are black)

**Comment by NekkonXD** [comment]
Do you know how to fix it? Or is it possible to fix it? My friend have adreno gpu and it doesnt have this issue and im really jelous with it. Anyway my  cpu is mt6737 and my gpu is Mali-T720MP2.

**Comment by NekkonXD** [comment]
I really want this fixed. Other stuff like black bullet holes and "vphysc error" text popup i have fix it. I appreciate your work.

**Comment by stephen-cusi** [comment]
> 我真的很想解决这个问题。我已经修复了其他东西，例如黑色弹孔和“vphysc 错误”文本弹出窗口。我很欣赏你的工作。

Use the new port to replace the new device
