### ISSUE TITLE
Where to get the latest apk?

### ISSUE THREAD

**Issue by Destroyer5150** [nillerusr/srceng-android#14]
I don't have a pc and can't make my own. I do google searches and just hope to get lucky. Can I get a link to the most updated builds please?

**Comment by abasgames** [comment]
https://drive.google.com/file/d/1yvuUzMY_X39NZQXjWHTSzKjk4Gjopuoc/view?usp=sharing

**Comment by Destroyer5150** [comment]
Thank you!!!! Will this same link always be latest?

**Comment by abasgames** [comment]
no

**Comment by glabz76** [comment]
@nillerusr were is the largest version of file? Could you help us with this?
