### ISSUE TITLE
Are the "main" obb's the same?

### ISSUE THREAD

**Issue by Destroyer5150** [nillerusr/srceng-android#16]
Noticed the hl2 and portal "main" obbs are the same size. If they're the same then can one be deleted to save space? And how about the episodes?

**Comment by Destroyer5150** [comment]
![Save Space HL2](https://user-images.githubusercontent.com/59759269/101584410-72dc9800-3992-11eb-9b62-836c36a07b64.jpg)

**Comment by nillerusr** [comment]
yeap
