### ISSUE TITLE
Will future updates be uploaded here?

### ISSUE THREAD

**Issue by Destroyer5150** [nillerusr/srceng-android#2]
Can I check here for regular releases? Also, I've tried V4 and it just crashes. Used the Shield obb files and proper directory. Even tried to unzip them. Thank you for the awesome work

Oh and I use an S9 snapdragon

**Comment by nillerusr** [comment]
V4 ver only for using with gltools lol.

**Comment by nillerusr** [comment]
V5 have very unstable graphic. Maybe I will upload beta version here in this month.

**Comment by Destroyer5150** [comment]
Cool that'll work. I'll test it and I understand what beta means. Keep up the good work and don't let these trolls get you down like they do to some. Looking forward to playing catch with dog on my phone with touch controls lol. Maybe even play Counter strike source and other mods in the future. Or play with Hammer?

**Comment by NekkonXD** [comment]
> Cool that'll work. I'll test it and I understand what beta means. Keep up the good work and don't let these trolls get you down like they do to some. Looking forward to playing catch with dog on my phone with touch controls lol. Maybe even play Counter strike source and other mods in the future. Or play with Hammer?

I dont think cs source will run it since nvidia doesn't port it yet.

**Comment by NekkonXD** [comment]
im also waiting for beta
