### ISSUE TITLE
Do not work on NVIDIA Shield 2019 Pro

### ISSUE THREAD

**Issue by benda95280** [nillerusr/srceng-android#20]
Hello,

First, hope you've got an happy christmas :)

It seems it do not works on Nvidia Shield Pro 2019.
App is able to found Obb file, but after launching, i stay on a black screen.
Tested with same source on my Xiaomi Phone with success.

Could you tell me what i can try/do to get it work ?

**Comment by Destroyer5150** [comment]
Nvidia shield has an official port and you don't need this to  play HL2 like the rest of us. In fact, it's what's being used by niller to give everyone else the ability to play.

**Comment by benda95280** [comment]
Yep, i'm having the official port, but i'm unable to have Custom Thing, or at least, french Voice ...
Works on my phone when i edit Obb File in SrcEng Folder :)

**Comment by magisk666** [comment]
你可以试试老版本的启动器

**Comment by benda95280** [comment]
> 你可以试试老版本的启动器
> You can try the old version of the launcher

? which one ?
