### ISSUE TITLE
Any plans for mod support?

### ISSUE THREAD

**Issue by Destroyer5150** [nillerusr/srceng-android#28]
First of all excellent work! Now since it's working good, are you planning on adding support for some popular mods? I'm thinking Counter Strike source (Gonna have to find a version that works) just for the offline bot matches and Gary's mod for starters. Maybe even zip them up like an obb file and put up some instructions on this github for people. Thanks bro and I wish I had this kind of talent so I could help.

**Comment by Truedufis20** [comment]
You can use mods by replacing the HL2 folder with the mod folder and renaming the mod folder to HL2. However, you have to use the command codes to go to the maps (as the chapter select is still FUBAR) and you can't save your game (or at least I couldn't).

**Comment by Martrubue** [comment]
Some mods doesnt work, but its great
