### ISSUE TITLE
Mouse Locking

### ISSUE THREAD

**Issue by ARealPear** [nillerusr/srceng-android#31]
I don't know if this is already a feature and I'm just overlooking it, but support for hiding the on-screen buttons and enabling mouse locking, and the normal binds for a connected mouse would be maybe useful

**Comment by nillerusr** [comment]
I know, i will add mouse support later

**Comment by ARealPear** [comment]
awesome!

**Comment by magisk6666** [comment]
ye

**Comment by nillerusr** [comment]
Works in new version

**Comment by magisk666** [comment]
> 在新版

> 在新版本中工作

it did work
