### ISSUE TITLE
Unable to read the contents of the custom folder

### ISSUE THREAD

**Issue by magisk666** [nillerusr/srceng-android#49]
![Screenshot_20211003_112735](https://user-images.githubusercontent.com/77914162/135738335-2149a721-da70-43ce-acc7-14d50655f5f5.jpg)
![Screenshot_20211003_112733](https://user-images.githubusercontent.com/77914162/135738336-8c754097-f4dd-43cb-a803-1950d7364ff2.jpg)
I think the previous version can load custom content
But the current version doesn't seem to work😭😭💤

**Comment by nillerusr** [comment]
Is it new port?

**Comment by magisk666** [comment]
> 是新港口吗？

You can look at the release date, it's an old port, but the old version seems to work.

**Comment by nillerusr** [comment]
Works now
