### ISSUE TITLE
Anybody ever try an UT2004 port to android?

### ISSUE THREAD

**Issue by Destroyer5150** [nillerusr/srceng-android#5]
Maybe you know someone that would give it a try? With all the mods available and bot support, and the fact that nobody has ever try

**Comment by kkw070504** [comment]
then why don't you develop it your self
(and don't upload thing's except about bug's and glitches it is not a place that we share about information's)

**Comment by Destroyer5150** [comment]
No bug's to report since no release yet. And very few people are skilled or interested enough to port anything to android. Just throwing out ideas to people who may be or has friends that may be.

**Comment by nillerusr** [comment]
This issue shouldn't be here
