### ISSUE TITLE
stuttering sound

### ISSUE THREAD

**Issue by HaguNS** [nillerusr/srceng-android#50]
I install today new apk and play hl2 i got problem with sound. My device is Asus Rog Phone 5 chipset is snapdragon 888 12/256gb Android 11.

**Comment by magisk666** [comment]
what

**Comment by HaguNS** [comment]
On Android 11 device Asus rp5 sound on menus or gamę is a crap bro.
Snapdragon 888 powerful :D

sob., 13 lis 2021, 11:43 użytkownik magisk666 ***@***.***>
napisał:

**Comment by magisk6666** [comment]
很抱歉我不是开发人员

**Comment by nillerusr** [comment]
I think that fixed in new port
