### ISSUE TITLE
A question about you

### ISSUE THREAD

**Issue by csreporter** [nillerusr/srceng-android#53]
Hello?l am a student from China.l am14 years old.l heared that many people know you did a launcher of css，they opened it. and play to have fun. l also want to play yours launcher to have fun together. please. l am so sorry to say this to you. because you must be angry now .but l like css very much. l hope you can share to me. please. 
thank you for your answers

**Comment by magisk666** [comment]
> 你好？我是中国学生。我14岁。我听说很多人知道你做了一个css的启动器，他们打开了它。玩得开心。我也想玩你的发射器一起玩。请。我很抱歉对你说这些。因为你现在一定很生气。但我非常喜欢css。我希望你能分享给我。请。 谢谢您的回答
あなたは中国語を話せますか？ 🍻

**Comment by magisk666** [comment]
> 你好？我是中国学生。我14岁。我听说很多人知道你做了一个css的启动器，他们打开了它。玩得开心。我也想玩你的发射器一起玩。请。我很抱歉对你说这些。因为你现在一定很生气。但我非常喜欢css。我希望你能分享给我。请。 谢谢您的回答

Вы мастер из Гонконга.Автор не обратит внимания на ваш вопрос.Мне очень жаль.

**Comment by nn-firc** [comment]
nope，想得美

**Comment by magisk666** [comment]
> 你好？我是中国学生。我14岁。我听说很多人都知道你做了一个css的启动器，他们打开了它。玩得开心。我也想玩你的发射器一起玩。请。我很抱歉对你说这些。因为你现在一定很生气。但是我非常喜欢css。我希望你可以分享给我。请。 谢谢您的回答

你是先辈好臭啊

**Comment by nillerusr** [comment]
no I can't share it.
