### ISSUE TITLE
How to support metamod & sourcemod in CS source offline game?

### ISSUE THREAD

**Issue by 1922828151** [nillerusr/srceng-android#64]
I tried adding the linux version of metamod and sourcemod to the game files, but nothing happened when I entered the game and entered meta list in the console.
![`C0_)Q(_966MP%1LJGFZ L2](https://github.com/nillerusr/srceng-android/assets/43509630/d4c05ae3-e8d6-4c49-b4d8-7880cf1cea6b)
![4J Z%(P YQ5H@WP59@J6XCB](https://github.com/nillerusr/srceng-android/assets/43509630/05e2f525-dbba-4f02-b952-53cefa768624)
Do I need to rebuild the game launcher?

**Comment by NanJinP** [comment]
I have the same problem, the console shows "Can't find the module - addons/metadata/bin/server". Have you resolved it?
我也一样的问题，控制台显示 "Can't find the module - addons/metamod/bin/server" 请问你解决了吗？

**Comment by 1922828151** [comment]
需要修复函数签名,这没啥好解决的,花时间找一下就行了.
